if: branch = master and not type IN (pull_request)
dist: trusty
sudo: false
language: minimal
before_install: true
install: true
before_script: true
script:
- echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
- if [ $(git diff --name-only HEAD^ | grep SubscribeOrions | wc -l) -ne 0 ]; then
  docker build --no-cache -t fiware/tool.subscribeorions SubscribeOrions/; docker
  push fiware/tool.subscribeorions; else echo "Nothing to build"; fi
env:
  global:
  - secure: kKchoapWX7oBzcsmOUqiVUH8Ivg18iQbR8sGEnOmlEmqaLwW1xFqN+l8LgSZr7pOzHR1WjhH/7ioF18JyJMD2vmTANfrk2lel8aQ2QEG17k1h07Cy9KclhuqKcuVYum+llCSmIA0ymfIOQptUrDlRkc1GpmsdnaIQSKoORof6558SJ3uYMp8SEG9nqirBmqMEKJGGYgseI+xJ5bxcboZnSiHUSM4s/20pZosoejVHFYrlXlrQy737LGFlVijCJTqmtoII3KgFvzpDBel+j0igu+jzR/Uv8L8+HVffYfomO98sT5FOY88brWKg8BDhUNH1ioQD8wWuyrRvUvM1814zzRkUYSZaKEEPoCKdq8uK3kpwNQuXA1iNPkdqfhYs+Vw7QId2JpRhYHGllO3n9LUdvMf0R+xLWXc8nYgZ7WNwKBKKDKB1WOytNBrjXVGUhfl0kel99BHidM1+EK8yE28UFp+vY1IFHmoc9Fvu7h/EZDrP6HC1Olvzqgr2hxv54i1q7aVvFABk4z7wdVyl0P0HJx7ZBxJ5ZMy23jbCybyAtU/Ehh0YBduQK8aWtag0+oWUUwfStj1oq3MEEoE7UJ5+Bi7LTorFMe8bpXdLmpqCgirXMEIVmG74H8c+2BuC7yT5F7CINKvEurXkISsFfEYKwX81PydJjMCLdda24Xj8IU=
  - secure: Y02Le2HBSv7zp4YuE8udCoEvjdOv0zu4j0zs/346UL/+2JgyTGjwEO9g/Id6la2D53oJODK83q9uQNzpdbYnFgt8jRV0zooZ++qK4qB1OP5G7kiu9fXkas+ypZH9TS8ltI/5lX22vcK0I1QHry7Jx3pROH4hWLuADlH983ZdrHEDDAxHPGUg792PmmtJpHfbZsJ3I86dKjJDvH2we3sJ3BVJ1V9RN+ADLr1LJTlyIcxLVZ9cwa4oVeEKvFYOPHjYsAAt9gF3Q9qbl5KbxWmfbSD6Rve0hZpOXIcRP1B/qJakblNSV1rJI3t1mQnXyes+Y+AJyv5pum0Wf4ZF3qB2vEnwGGlCi6Lz3z8mD+eMGbWtwUDZkWHF+/xIpKCWsI0tgJOn/xKpDbYxIZjY8alsUCIlw2Y0/kMsTphLgHuTK3HY8qCsnyr6ZkK1Adceumpe1uMjDAdt0/MHqOXIlTiM5hGwdhli2DSuUEMhiND3vvkbWBOaAer+GlydFWIXpDYE9R9kUVSjAxXOiIgEsp1mjAiWvbm5QLpef7VuogSFp6hkTtcH+J4gjjG9w2CbE7TtD+622G1a9UFMHDLGEPcG2zWNYZZ1BY3ym03izcatstTKQuQaFzx9Uc66ms7x886ValkvxrmVd5qKqUAdoRMG/viSkHQsaUqc9FmEEu9iJ2E=
