if: branch = master and not type IN (pull_request)
dist: trusty
sudo: false
language: minimal
before_install: true
install: true
before_script: true
script:
- echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
- if [ $(git diff --name-only HEAD^ | grep SubscribeOrions | wc -l) -ne 0 ];
  then
    docker build --no-cache -t fiware/tool.subscribeorions SubscribeOrions/;
    docker push fiware/tool.subscribeorions;
  else
    echo "Nothing to build";
  fi
env:
  global:
  - secure: 5ii8yD1AYSMZfSthvY613hAy5JqZzk8NjunY6zrzJB+iJApjpQPZMlVLhdnkhCArrqn77x1B+i18QJGQr8ItRUs/N1pWqls/AQatDrhjnGhOuNwIkW3BihE0sB/VciDiQncvE/jGUnAo7klYp7PLuNMwBLItj8f0Y44D8IEPu5tQP2aWIA2wG3Su+y2GlzPqoqtbpjvTbrBiO7wMZRYIDIBFQSH3HDfEjHkAIP/3MQGMbMpbBSnKeqMTiCIGF4MeNMHGLoSyiBMeBIJpbZDEdKIB784iJcLrEDr55+mI1ldk5ZZpcCZO55jTGOzT8WySCgRRakuO8wVUx0RqJIMlVc2m3PeusJ83ZhFZ13y9m+Ob36iPUAjGUP/5jUjye7QXf4D/prOMogtKURrE7G3UN4808/zOD/ypPI8lnoju/0dNCEpcKlqXd3TcNxHVzNpB9z9GD43lSHfuIV77iOIIeYwe6Wl4MCArR9epSS0RJ5z9z7uukzssxfpCrMtiWSpjP2qOAUIzi8VajIJYWu/6hK4XBMfvdiSms55hrFxw/POkhX4um+DwZDBBRqEY24LcXgE1vivf+gQLxn9PPIraZiQcfodqkw+tmpr/sbdB5znko6aVvzUk9BKiwFR2xg3PP0U/CVGBEZ/oVsM4wJOuBsREGD8+836zNc0JA3H4aWU=
  - secure: igZfMN+6rY14DXQiOy4KUdn9KcieVK8xqG6EmSBUxQKaI0JWOg4XiirvCkdqTEA7XXNXNkchpCPLmoe4eybWdJGcPh5pOEkw7IV2G2xwC1hJ42ZOe/KK//rus83u43bFowMBAK+XJMaPj6PabzQI+7DyLI3fVQLuPfnc48D1/JLq6LRyNN6ots3Gcpm5hCIIIyKet7okYzagyPR/shDUwNckQlFeQIHn/zWIoA4bX52Wf+NIuEgQPomDTLMwGqUQtkZim53ZEYGNLhgtGLO1iJPz8C6rkb7SY3zbkm+l1nLt4Dm1PF53YudzfsuwfZOfZxFMb4NWNTp8Wmp+7oLOpPyBECtiba0d+KMGlMyZVO92mai0l3DehWy/EfBXUwzG4g1CD6gTYxTyeJ9MA53mJwzpGXiqaumNU6Q2p/fwHjoTA9C71I3mr5jCwQr1wQLcbxDQKZl3Tk+Bm3BQhOqWJb3Br/8f1unlhR7lPYkEWmv9s5G3sZSxtdM7YIxAOGR3A7SOfTJL5OzeE87apTTlxNCMAu1DGdTMBYnqCjEVAdXle0nrlm3Is5IDRAkcy9v8JmizlfdFkmwO94jmAUUWiM8R/AC3vla1PYGcnVvLAB5c7pMlQ3DFXwsv130dZGxB/DtzH6xE3YgwOc0VBv4aFDvrzVSQlXmI2cM0hMgIYrc=
